filter:
  excluded_paths: [vendor/*, tests/*]
checks:
  php:
    code_rating: true
    duplication: true
before_commands:
  - 'composer install --dev --prefer-source'
build:
  nodes:
    coverage:
      tests:
        override:
          - php-scrutinizer-run
          - command: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml; if [ "$?" -gt "2" ]; then exit 1; fi'
            coverage:
              file: clover.xml
              format: php-clover
            idle_timeout: 1800
